language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t anhnt2310/docker-react -f Dockerfile.dev . 

script: 
  - docker run -e CI=true anhnt2310/docker-react yarn test